"""crear tablas iniciales

Revision ID: 306d0eef780e
Revises: 
Create Date: 2024-12-06 11:39:02.960719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '306d0eef780e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id_item', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('anio_publicacion', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('autor', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('edicion', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_item'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prestamos',
    sa.Column('id_prestamo', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_prestamo', sa.DATE(), nullable=True),
    sa.Column('devuelto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['items.id_item'], name='prestamos_ibfk_1'),
    sa.PrimaryKeyConstraint('id_prestamo'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
