"""Agregar herencia para libros y revistas

Revision ID: aa828613e72a
Revises: 306d0eef780e
Create Date: 2024-12-06 14:30:06.894415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa828613e72a'
down_revision: Union[str, None] = '306d0eef780e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prestamos')
    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('anio_publicacion', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.ENUM('Libro', 'Revista'), nullable=False),
    sa.Column('autor', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('edicion', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prestamos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_item', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_prestamo', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('devuelto', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_item'], ['items.id'], name='prestamos_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
